migrate to gopkg.in
src-d/go-errors pull request #6
Opened 2017-05-10 12:50 UTC by alcortesm

Part of https://github.com/src-d/backlog/issues/700.

2017-05-11 08:23 UTC, smola requested changes

2017-05-11 08:23 UTC, smola commented on .travis.yml
> -  - rm -rf $GOPATH/src/srcd.works
This is still needed, but with `gopkg.in`. That's why tests fail.

2017-05-16 08:09 UTC, alcortesm commented on .travis.yml
> -  - rm -rf $GOPATH/src/srcd.works
Ok!, fixing it right now!

2017-05-22 16:02 UTC, smola approved these changes

2017-05-22 16:20 UTC, merged